# v3からの差分:
# - flutter_eval を ^0.6.1 から ^0.8.2 に更新
#   (0.6系は最新のFlutterでビルドエラーになるため)

name: darteditor
description: iPad/Android/Webで使えるDartコードエディタ
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.0
  dart_eval: any
  flutter_eval: ^0.8.2

flutter:
  uses-material-design: true
