# v2からの差分:
# - 仮想デバイス表示用に flutter_eval を追加
# - dart_eval のバージョン指定を any に変更(flutter_eval との競合を避けるため)

name: darteditor
description: iPad/Android/Webで使えるDartコードエディタ
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.0
  dart_eval: any
  flutter_eval: ^0.6.1

flutter:
  uses-material-design: true
